name: Sitemap Maintainer

on:
  push:
    branches: [ main, master ]
    paths:
      - "sitemap-*.xml"
      - "scripts/**"
  schedule:
    - cron: "17 6 * * 1"   # Mondays 06:17 UTC
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run updater
        run: |
          python3 scripts/update_sitemaps.py

      - name: Commit changes (if any)
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(sitemap): alphabetize + refresh <lastmod> to today"
          file_pattern: "sitemap-*.xml"
